# backup_config.cfg
backup_config = [
    ("jackett", "jackett-config-backup", "config"),
    ("sonarr", "sonarr-backup", "config"),
    ("radarr", "radarr-backup", "config"),
    ("ombi-dm", "ombi-dm-backup", "config"),
    ("ombi-mu", "ombi-mu-backup", "config"),
    ("plex-dm", "plex-dm-backup", "config"),
    ("plex-mu", "plex-mu-backup", "config"),
    ("tautulli-dm", "tautulli-dm-backup", "config"),
    ("portainer", "portainer-backup", "data"),
    ("varken", "varken-backup", "config"),
    ("grafana", "grafana-backup", "var/lib/grafana"),
    ("influxdb", "influxdb-backup", "var/lib/influxdb"),
    ("prometheus", "prometheus-backup", "etc/prometheus prometheus"),
    ("swag", "swag-backup", "config"),
    ("paperless-ngx-webserver-1", "paperless-ngx-backup", "usr/src/paperless/data usr/src/paperless/media"),
    ("paperless-ngx-db-1", "paperless-ngx-db-backup", "var/lib/postgresql/data"),
    ("semaphore-mysql", "semaphore-mysql-backup", "var/lib/mysql"),
    ("torrent_svcs-rtorrent-rutorrent-1", "rtorrent-rutorrent-backup", "data passwd"),
]